[Stella][BugFix] Fix the NoClassDefFoundError caused by the Parquet version upgrade in Paimon dependency Link: https://code.alibaba-inc.com/soe/stella/codereview/22592963